-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.attestation_campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  target_type text DEFAULT 'all'::text,
  target_department text,
  target_role text,
  due_date date,
  training_url text,
  status text DEFAULT 'open'::text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT attestation_campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT attestation_campaigns_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT attestation_campaigns_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id)
);
CREATE TABLE public.attestations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role_snapshot text,
  acknowledged_at timestamp with time zone,
  ip text,
  status text DEFAULT 'pending'::text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  comment text,
  CONSTRAINT attestations_pkey PRIMARY KEY (id),
  CONSTRAINT attestations_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT attestations_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.attestation_campaigns(id),
  CONSTRAINT attestations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  actor uuid,
  actor_email text,
  entity_type text NOT NULL,
  entity_id text,
  action text NOT NULL,
  before_data jsonb,
  after_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.control_evidences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  control_id uuid NOT NULL,
  file_url text NOT NULL,
  version text,
  status text NOT NULL DEFAULT 'pending_review'::text CHECK (status = ANY (ARRAY['pending_review'::text, 'approved'::text, 'rejected'::text])),
  uploaded_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_comment text,
  expires_at date,
  org_id uuid,
  CONSTRAINT control_evidences_pkey PRIMARY KEY (id),
  CONSTRAINT control_evidences_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id),
  CONSTRAINT control_evidences_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT control_evidences_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.control_exceptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  control_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['na'::text, 'exception'::text])),
  approver uuid,
  rationale text,
  expires_at date,
  compensating_control_id uuid,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'closed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  org_id uuid,
  CONSTRAINT control_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT control_exceptions_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id),
  CONSTRAINT control_exceptions_approver_fkey FOREIGN KEY (approver) REFERENCES public.profiles(id),
  CONSTRAINT control_exceptions_compensating_control_id_fkey FOREIGN KEY (compensating_control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.control_tests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  control_id uuid NOT NULL,
  period_start date,
  period_end date,
  sample_size integer,
  exceptions_found integer,
  conclusion text CHECK (conclusion = ANY (ARRAY['design_only'::text, 'effective'::text, 'ineffective'::text])),
  tested_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  org_id uuid,
  CONSTRAINT control_tests_pkey PRIMARY KEY (id),
  CONSTRAINT control_tests_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id),
  CONSTRAINT control_tests_tested_by_fkey FOREIGN KEY (tested_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.controls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  framework_id uuid,
  code text,
  description text,
  status text DEFAULT 'not_compliant'::text CHECK (status = ANY (ARRAY['compliant'::text, 'partial'::text, 'not_compliant'::text])),
  evidence_url text,
  updated_at timestamp with time zone DEFAULT now(),
  owner uuid,
  frequency text CHECK (frequency = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'quarterly'::text, 'annual'::text, 'ad-hoc'::text])),
  type text CHECK (type = ANY (ARRAY['preventive'::text, 'detective'::text, 'corrective'::text])),
  nature text CHECK (nature = ANY (ARRAY['manual'::text, 'automated'::text, 'hybrid'::text])),
  objective text,
  last_tested_date date,
  effectiveness text CHECK (effectiveness = ANY (ARRAY['design_only'::text, 'effective'::text, 'ineffective'::text])),
  scope_assets ARRAY DEFAULT ARRAY[]::text[],
  org_id uuid,
  CONSTRAINT controls_pkey PRIMARY KEY (id),
  CONSTRAINT controls_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.frameworks(id),
  CONSTRAINT controls_owner_fkey FOREIGN KEY (owner) REFERENCES public.profiles(id)
);
CREATE TABLE public.findings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  severity text DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'closed'::text])),
  risk_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  owner uuid,
  sla_due_date date,
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT findings_pkey PRIMARY KEY (id),
  CONSTRAINT findings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT findings_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT findings_owner_fkey FOREIGN KEY (owner) REFERENCES public.profiles(id)
);
CREATE TABLE public.framework_mappings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  source_framework_id uuid NOT NULL,
  target_framework_id uuid NOT NULL,
  source_control_id uuid NOT NULL,
  target_control_id uuid NOT NULL,
  rationale text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT framework_mappings_pkey PRIMARY KEY (id),
  CONSTRAINT framework_mappings_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT framework_mappings_source_framework_id_fkey FOREIGN KEY (source_framework_id) REFERENCES public.frameworks(id),
  CONSTRAINT framework_mappings_target_framework_id_fkey FOREIGN KEY (target_framework_id) REFERENCES public.frameworks(id),
  CONSTRAINT framework_mappings_source_control_id_fkey FOREIGN KEY (source_control_id) REFERENCES public.controls(id),
  CONSTRAINT framework_mappings_target_control_id_fkey FOREIGN KEY (target_control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.frameworks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  CONSTRAINT frameworks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  plan text DEFAULT 'free'::text CHECK (plan = ANY (ARRAY['free'::text, 'pro'::text, 'enterprise'::text])),
  owner_id uuid,
  updated_at timestamp with time zone DEFAULT now(),
  plan_status text DEFAULT 'inactive'::text CHECK (plan_status = ANY (ARRAY['inactive'::text, 'trialing'::text, 'active'::text, 'past_due'::text, 'canceled'::text])),
  stripe_customer_id text,
  stripe_subscription_id text,
  stripe_price_id text,
  current_period_end timestamp with time zone,
  canceled_at timestamp with time zone,
  brand_color text DEFAULT '#4f46e5'::text,
  logo_url text,
  slug text,
  custom_domain text,
  custom_domain_status text DEFAULT 'pending'::text CHECK (custom_domain_status = ANY (ARRAY['pending'::text, 'active'::text, 'error'::text])),
  custom_domain_verified_at timestamp with time zone,
  sso_google_enabled boolean DEFAULT false,
  sso_azure_enabled boolean DEFAULT false,
  scim_status text DEFAULT 'disabled'::text CHECK (scim_status = ANY (ARRAY['disabled'::text, 'ready'::text, 'active'::text])),
  scim_provisioning_token text,
  scim_last_sync_at timestamp with time zone,
  risk_appetite_threshold integer DEFAULT 12,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.plan_limits (
  plan text NOT NULL,
  max_users integer,
  max_risks integer,
  max_frameworks integer,
  CONSTRAINT plan_limits_pkey PRIMARY KEY (plan)
);
CREATE TABLE public.policies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  owner uuid,
  version text,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'archived'::text])),
  review_date date,
  file_url text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  effective_date date,
  attestation_percent numeric DEFAULT 0,
  exceptions_count integer DEFAULT 0,
  updated_at timestamp with time zone DEFAULT now(),
  tags ARRAY DEFAULT '{}'::text[],
  classification text DEFAULT 'Internal'::text,
  author uuid,
  supersedes_id uuid,
  retention_period_months integer DEFAULT 24,
  CONSTRAINT policies_pkey PRIMARY KEY (id),
  CONSTRAINT policies_owner_fkey FOREIGN KEY (owner) REFERENCES public.profiles(id),
  CONSTRAINT policies_author_fkey FOREIGN KEY (author) REFERENCES public.profiles(id),
  CONSTRAINT policies_supersedes_id_fkey FOREIGN KEY (supersedes_id) REFERENCES public.policies(id)
);
CREATE TABLE public.policy_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  approver uuid NOT NULL,
  comment text,
  decided_at timestamp with time zone DEFAULT now(),
  status text DEFAULT 'approved'::text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT policy_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT policy_approvals_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT policy_approvals_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT policy_approvals_approver_fkey FOREIGN KEY (approver) REFERENCES public.profiles(id)
);
CREATE TABLE public.policy_controls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  control_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT policy_controls_pkey PRIMARY KEY (id),
  CONSTRAINT policy_controls_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT policy_controls_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT policy_controls_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.policy_exceptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  requester uuid,
  scope text,
  rationale text,
  approver uuid,
  expiry date,
  status text DEFAULT 'open'::text,
  linked_risk_id uuid,
  linked_control_id uuid,
  linked_asset text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT policy_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT policy_exceptions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT policy_exceptions_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT policy_exceptions_requester_fkey FOREIGN KEY (requester) REFERENCES public.profiles(id),
  CONSTRAINT policy_exceptions_approver_fkey FOREIGN KEY (approver) REFERENCES public.profiles(id),
  CONSTRAINT policy_exceptions_linked_risk_id_fkey FOREIGN KEY (linked_risk_id) REFERENCES public.risks(id),
  CONSTRAINT policy_exceptions_linked_control_id_fkey FOREIGN KEY (linked_control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.policy_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  file_url text,
  file_name text,
  file_type text,
  file_size integer,
  version text,
  status text DEFAULT 'active'::text,
  uploaded_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  storage_path text,
  org_id uuid NOT NULL,
  CONSTRAINT policy_files_pkey PRIMARY KEY (id),
  CONSTRAINT policy_files_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT policy_files_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id)
);
CREATE TABLE public.policy_versions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  policy_id uuid NOT NULL,
  version text NOT NULL,
  change_summary text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid NOT NULL,
  CONSTRAINT policy_versions_pkey PRIMARY KEY (id),
  CONSTRAINT policy_versions_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT policy_versions_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id),
  CONSTRAINT policy_versions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text,
  email text,
  role text DEFAULT 'viewer'::text CHECK (role = ANY (ARRAY['admin'::text, 'manager'::text, 'viewer'::text])),
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.risk_acceptance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  risk_id uuid,
  actor uuid,
  action text CHECK (action = ANY (ARRAY['requested'::text, 'accepted'::text, 'rejected'::text, 'expired'::text, 'reviewed'::text])),
  rationale text,
  expiry date,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT risk_acceptance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT risk_acceptance_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT risk_acceptance_logs_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_acceptance_logs_actor_fkey FOREIGN KEY (actor) REFERENCES public.profiles(id)
);
CREATE TABLE public.risk_controls (
  risk_id uuid NOT NULL,
  control_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT risk_controls_pkey PRIMARY KEY (risk_id, control_id),
  CONSTRAINT risk_controls_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT risk_controls_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_controls_control_id_fkey FOREIGN KEY (control_id) REFERENCES public.controls(id)
);
CREATE TABLE public.risk_policies (
  risk_id uuid NOT NULL,
  policy_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT risk_policies_pkey PRIMARY KEY (risk_id, policy_id),
  CONSTRAINT risk_policies_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT risk_policies_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_policies_policy_id_fkey FOREIGN KEY (policy_id) REFERENCES public.policies(id)
);
CREATE TABLE public.risk_review_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  risk_id uuid,
  reviewer uuid,
  reviewed_at timestamp with time zone DEFAULT now(),
  note text,
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid CHECK (org_id IS NOT NULL) NOT VALI),
  CONSTRAINT risk_review_logs_pkey PRIMARY KEY (id),
  CONSTRAINT risk_review_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT risk_review_logs_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT risk_review_logs_reviewer_fkey FOREIGN KEY (reviewer) REFERENCES public.profiles(id)
);
CREATE TABLE public.risks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  owner uuid,
  likelihood integer CHECK (likelihood >= 1 AND likelihood <= 5),
  impact integer CHECK (impact >= 1 AND impact <= 5),
  score integer DEFAULT (likelihood * impact),
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'closed'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  inherent_likelihood integer CHECK (inherent_likelihood >= 1 AND inherent_likelihood <= 5),
  inherent_impact integer CHECK (inherent_impact >= 1 AND inherent_impact <= 5),
  category text,
  cause text,
  consequence text,
  affected_asset text,
  department text,
  next_review_date date,
  delegate_owner uuid,
  last_reviewed_at timestamp with time zone,
  acceptance_status text DEFAULT 'none'::text CHECK (acceptance_status = ANY (ARRAY['none'::text, 'requested'::text, 'accepted'::text, 'rejected'::text, 'expired'::text])),
  acceptance_approver uuid,
  acceptance_rationale text,
  acceptance_expiry date,
  acceptance_requested_at timestamp with time zone,
  acceptance_decided_at timestamp with time zone,
  closure_rationale text,
  closure_date date,
  org_id uuid NOT NULL,
  acceptance_requester uuid,
  residual_likelihood integer CHECK (residual_likelihood >= 1 AND residual_likelihood <= 5),
  residual_impact integer CHECK (residual_impact >= 1 AND residual_impact <= 5),
  CONSTRAINT risks_pkey PRIMARY KEY (id),
  CONSTRAINT risks_acceptance_requester_fkey FOREIGN KEY (acceptance_requester) REFERENCES public.profiles(id),
  CONSTRAINT risks_owner_fkey FOREIGN KEY (owner) REFERENCES public.profiles(id),
  CONSTRAINT risks_delegate_owner_fkey FOREIGN KEY (delegate_owner) REFERENCES public.profiles(id),
  CONSTRAINT risks_acceptance_approver_fkey FOREIGN KEY (acceptance_approver) REFERENCES public.profiles(id),
  CONSTRAINT risks_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  assigned_to uuid,
  related_type text CHECK (related_type = ANY (ARRAY['risk'::text, 'control'::text, 'policy'::text])),
  related_id uuid,
  due_date date,
  status text DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'done'::text])),
  created_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id)
);
CREATE TABLE public.treatment_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  risk_id uuid,
  action_title text NOT NULL,
  action_type text DEFAULT 'mitigate'::text CHECK (action_type = ANY (ARRAY['accept'::text, 'mitigate'::text, 'transfer'::text, 'avoid'::text])),
  description text,
  responsible_user uuid,
  due_date date,
  status text DEFAULT 'not_started'::text CHECK (status = ANY (ARRAY['not_started'::text, 'in_progress'::text, 'done'::text])),
  cost_estimate numeric,
  evidence_url text,
  created_at timestamp with time zone DEFAULT now(),
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  blocked boolean DEFAULT false,
  blocked_reason text,
  org_id uuid,
  CONSTRAINT treatment_plans_pkey PRIMARY KEY (id),
  CONSTRAINT treatment_plans_risk_id_fkey FOREIGN KEY (risk_id) REFERENCES public.risks(id),
  CONSTRAINT treatment_plans_responsible_user_fkey FOREIGN KEY (responsible_user) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_invite_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  org_id uuid NOT NULL,
  inviter_id uuid NOT NULL,
  invitee_email text NOT NULL,
  invitee_id uuid,
  role text CHECK (role = ANY (ARRAY['admin'::text, 'manager'::text, 'viewer'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  accepted_at timestamp with time zone,
  accepted_ip text,
  CONSTRAINT user_invite_logs_pkey PRIMARY KEY (id),
  CONSTRAINT user_invite_logs_org_id_fkey FOREIGN KEY (org_id) REFERENCES public.organizations(id),
  CONSTRAINT user_invite_logs_inviter_id_fkey FOREIGN KEY (inviter_id) REFERENCES public.profiles(id),
  CONSTRAINT user_invite_logs_invitee_id_fkey FOREIGN KEY (invitee_id) REFERENCES public.profiles(id)
);